DROP PROCEDURE IF EXISTS IPaleta;

DELIMITER $$
CREATE PROCEDURE IPaleta(IN PCOLOR VARCHAR(150), IN FCOLOR VARCHAR(150), IN ID_USUARIO INT) 

BEGIN 
    INSERT INTO Configuracion_Paleta(Pen_color, Fill_color, id_usuario)
    VALUES (PCOLOR, FCOLOR, ID_USUARIO);
END$$
DELIMITER ;